### ISSUE TITLE
Implement a ts client to send/receive messages over rmb relays

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb-sdk-ts#1]
- [x] direct client
- [x] client to use rmb peers

**Comment by amiraabouhadid** [comment]
current ts rmb client can do the following:
- connect to rmb-relay using jwt authentication
- create message envelope, encrypt & sign envelope then send it to chain twin or rmb-peer 
- receive response from either chain twin or rmb-peer and decrypt it (show error if any)
next steps are:
- add response verification and mapping to request ID on client
- add retrieval of twin ID from chain

**Comment by amiraabouhadid** [comment]
current ts rmb client can do the following:
- [x] connect to rmb-relay using jwt authentication
- [x] create message envelope, encrypt & sign envelope then send it to chain twin or rmb-peer 
- [x] receive response from either chain twin or rmb-peer and decrypt it (show error if any)
- [x] add retrieval of twin ID from chain


next steps are:
- [ ] add response verification and mapping to request ID on client

**Comment by amiraabouhadid** [comment]
done and merged onto master branch
