### ISSUE TITLE
add protection on the close method to make sure the connection is established

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb-sdk-ts#22]
also, we can call `close` method `disconnect` to be consistent as we have `connect` for opening the connection

**Comment by amiraabouhadid** [comment]
was resolved in https://github.com/threefoldtech/rmb-sdk-ts/pull/24

**Comment by mohamedamer453** [comment]
Verified from https://github.com/threefoldtech/rmb-sdk-ts/blob/development/lib/client.ts#L93&L137 

The disconnect logic was added and conditions were added to check if the connection were established or not.

And as originally mentioned in the issue the function name is now `disconnect` not `close`  for the sake of consistency.
