### ISSUE TITLE
client stuck in connection if the ws url is wrong

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb-sdk-ts#23]

**Comment by AhmedHanafy725** [comment]
retries are added to the client initialization and it should throw an error if it couldn't connect

**Comment by mohamedamer453** [comment]
Verified from https://github.com/threefoldtech/rmb-sdk-ts/blob/development/lib/client.ts#L32 

The client module now has a retry logic, the amount of desired retires can be passed to the `retries` variable while creating the constructor and [it will retry the connection for the mentioned amount of retries and then throws an error and disconnects if the url is wrong.](https://github.com/threefoldtech/rmb-sdk-ts/blob/development/lib/client.ts#L214&L226)
