### ISSUE TITLE
[direct-client] ping/pong and timeout

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/rmb-sdk-ts#25]
https://github.com/threefoldtech/rmb-sdk-go/issues/5

**Comment by MohamedElmdary** [comment]
For sending a ping command on browser we need to create a frame with opcode 0x9 (message doesn't matter) but creating frames isn't implemented yet on browser

![image](https://user-images.githubusercontent.com/31689104/222428156-04e597ef-b21d-41dd-80d7-537f9e738a56.png)

**Comment by muhamadazmy** [comment]
The relay now support higher level (app level) ping/pong message. it can be done by sending an Envelope with a new request type (ping) 
it does not require Signing, or destination address. The Relay will then replay with an empty Pong message.

go implementation here https://github.com/threefoldtech/rmb-sdk-go/blob/main/direct/direct.go#L406

**Comment by mohamedamer453** [comment]
Verified on devnet.

I tried to send a ping request and i successfully received a pong.

![image](https://user-images.githubusercontent.com/101194226/226950057-ebb0ef0f-03c3-4e26-a11d-2e433d78e511.png)
