### ISSUE TITLE
Store the message id in the responses map before sending the request

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb-sdk-ts#26]
this is to avoid the race condition that may happen if the response came before setting the id on the responses map, so we don't lose it

https://github.com/threefoldtech/rmb-sdk-ts/blob/7870618dd6c207eab65d188f32769a2c1bf68d08/lib/client.ts#L157

**Comment by mohamedamer453** [comment]
Verified from https://github.com/threefoldtech/rmb-sdk-ts/pull/27

The id is now stored before the message is sent.
