### ISSUE TITLE
Open one ws connection for tfchain while connecting to the client

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb-sdk-ts#29]
instead of creating a connection to tfchain and closing it with each message sent, make one connection while connecting to the relay and close it when closing the connection to the relay

**Comment by mohamedamer453** [comment]
Verified.

In the client module the [`createConnection`](https://github.com/threefoldtech/rmb-sdk-ts/blob/development/lib/client.ts#L53) function creates a single ws connection and in the [`connect`](https://github.com/threefoldtech/rmb-sdk-ts/blob/development/lib/client.ts#L90) function a disconnection logic was added as mentioned and verified in #23 thus only a single connection will be created to the chain while connecting to the client and it will be closed when the connection to the relay is closed.
