### ISSUE TITLE
Update twin if it doesn't have a public key

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb-sdk-ts#30]
like the go sdk does
https://github.com/threefoldtech/rmb-sdk-go/blob/020c681907234a0e03eee0cb8223728ab278d15f/direct/direct.go#L106

**Comment by xmonader** [comment]
blocked on https://github.com/threefoldtech/rmb-sdk-ts/pull/20

**Comment by amiraabouhadid** [comment]
done, waiting for review
