### ISSUE TITLE
add twin pk on the chain if twin doesnt have publick key

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/rmb-sdk-ts#40]
instead of just generating a pk, change the twin's pk on the chain

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/rmb-sdk-ts/issues/40

**Comment by A-Harby** [comment]
Verified.
Updated Twin PK to null.
![image](https://user-images.githubusercontent.com/109473873/226614808-e79aa9c2-447d-47f0-8c80-f4c95313f377.png)
Then run RMB 
![image](https://user-images.githubusercontent.com/109473873/226637646-4c08f06b-5e1f-41fe-bce7-0130a2b57acc.png)
and it updated twin pk on chain
![image](https://user-images.githubusercontent.com/109473873/226627511-f0c45689-a079-4e46-9736-61a46c35b6ec.png)
