### ISSUE TITLE
New account with no pk

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/rmb-sdk-ts#47]
### Search first

Search for similar issues first, if not complete the following template
No similar issue was found

### Description

A newly created account on the dashboard was used in the rmb-sdk-ts but was found to have an invalid pk of ```0x```.

### Steps to reproduce

1. create new account on polkadot
2. create twin on dashboard
3. enter account mnemonic into[ node.ts ](https://github.com/threefoldtech/rmb-sdk-ts/blob/81b30d8c4c9ab6a59b5098d6163418f1bc20d8f6/examples/direct/node.ts#L6)examples script in rmb-sdk-ts 
4. run ```yarn && yarn start```

### Logs/Alerts

```
yarn run v1.22.19
$ ts-node --project ./tsconfig-node.json ./examples/direct/node.ts
2023-03-26 15:25:35        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2023-03-26 15:25:35        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
/home/amira/cs/rmb-sdk-ts/examples/direct/node.ts:21
        throw new Error(`RMB Client connection failed due to ${err}`)
              ^
Error: RMB Client connection failed due to 401 e2e encryption error: k256: malformed public key
    at main (/home/amira/cs/rmb-sdk-ts/examples/direct/node.ts:21:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by AhmedHanafy725** [comment]
a fix was done on the dashboard to avoid this case of having the public key as an empty string

**Comment by A-Harby** [comment]
Verified 
![image](https://user-images.githubusercontent.com/109473873/228585798-6d174fcf-463a-432d-98d7-658a5d99b757.png)
